activemq:
  authentication:
    create: true  # Set to false to not create a secret for credentials
    existingSecret: ""  # Specify existing secret name for credentials, if not provided will create new secret
    # Default credentials (used only if existingSecret is not provided)
    defaultUsername: "admin"  # Default username if not using existing secret
    defaultPassword: "admin"  # If empty, will generate random password
  persistence:
    claimName: pvc-activemq-artemis
    size: 10Gi
    storageClass:
      name: "hostpath"
  monitoring:
    enabled: true
    jmx:
      enabled: true